### ISSUE TITLE
Feature request: Support KMP

### ISSUE THREAD

**Issue by doolle89** [dokar3/ChipTextField#117]
Hi, It would be nice if you could update the project to support KMP, probably it doesn't require much work since m3 is already supported there. From what I saw the only Android specific thing would be [awaitFrame](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-android/kotlinx.coroutines.android/await-frame.html)

**Comment by dokar3** [comment]
Good suggestion! But I haven't stepped into KMP yet, it will be KMP-compatible when I'm ready.

or

If anyone has an interest in this can create a PR for us, I've been lacking time to learn KMP recently.

**Comment by dokar3** [comment]
Initial KMP support is available in v0.7.0-alpha01: https://github.com/dokar3/ChipTextField/releases/tag/v0.7.0-alpha01
iOS is not currently supported. Opened another issue to track #131

**Comment by Deaths-Door** [comment]
For anyone interested, I had created a [KMP Compatible with M3](https://github.com/Deaths-Door/advanced-chiptextfield-compose-kmp) (at the time , it was not supported) some time ago , and it seems to be working fine.

**Note** : This was a copy of a *now* old version , so unless there were changes , it should work
