### ISSUE TITLE
OutlinedChipTextField auto can't be removed- when using in a form

### ISSUE THREAD

**Issue by ashishkr2534** [dokar3/ChipTextField#74]
i am using this libarary and to get  chips in outlined textfields . (OutlinedChipTextFiled)
while using this with other compose outlined TextFields it get the focus when navigation to that form screen.

Trying to stop that from happening. as my top field are getting scrolled to bottom and get focused on OutlinedChipTextField().

Any Help/support/feedback on this -

**Comment by dokar3** [comment]
Thank you for reporting, it seems a bug while I was trying to deal with the focus between chips and the text field, should be fixed soon after dispatching a fix.

**Comment by ashishkr2534** [comment]
@dokar3  Is there any work around-  around this, or i can somehow disable focus at initial call.

One more thing , i was trying to populate chips by passing array list from api but seems complex to do so

**Comment by ashishkr2534** [comment]
Thank You @dokar3  Really Appreciate it....

**Comment by dokar3** [comment]
@ashishkr2534 You are welcome, feel free to report.

**Comment by ashishkr2534** [comment]
Thank You @dokar3  . Latest update ( V0.4.6 ) did solved  my auto focus issue.  really Appreciate it : )

///
Will also use prePopulatio on chip with list.

**Comment by dokar3** [comment]
You are welcome, happy to hear it's been solved.
