### ISSUE TITLE
Add support for material 3

### ISSUE THREAD

**Issue by mahmoud-abdallah863** [dokar3/ChipTextField#95]
Can't use this library on material 3 currently

In my app I am using material 3 only. I don't want to mix both material 3 and 2.

**Comment by dokar3** [comment]
Thanks for the suggestion, will ship an M3 artifact when I have time.

**Comment by mahmoud-abdallah863** [comment]
Great. I'm willing to help in this

**Comment by dokar3** [comment]
v0.6.0 is out with Material 3 support: https://github.com/dokar3/ChipTextField/releases/tag/v0.6.0
